serilog-contrib/serilog-sinks-elasticsearch

src/Serilog.Sinks.Elasticsearch/Serilog.Sinks.ElasticSearch.nuspec
NuGet will now use the sink icon instead of the standard Serilog icon.
=> Changed NuGet icon URL to sink icon

src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticSearchLogShipper.cs
Fixes an issue where the index decider was not properly used with pusing events thorugh the ElasticLogShipper.
=> Uses the IndexDecider to decide index name when pushing to index.

src/Serilog.Sinks.Elasticsearch/LoggerConfigurationElasticSearchExtensions.cs
Added a simple overload with the parameters @mivano suggested. I made the index format and template registration optional to remain in the spirit of bare minimum configuration (server address only) required.
If this gets merged in the "Breaking changes for version 2" section in the readme should probably be updated to reflect that basic appSettings configuration is possible.
=> Added overload for appSettings configuration to resolve #425

src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/DurableElasticSearchSink.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticSearchLogShipper.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticSearchSink.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchSinkState.cs
when using the durable sink, because we should not do this synchronously on the initializing thread when logging is initialized
=> delay auto-register-template-if-necessary call to the first timer tick

src/Serilog.Sinks.Elasticsearch/Serilog.Sinks.Elasticsearch.csproj, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchJsonFormatter.cs
Dots are not allowed in Field Names, replaces '.' with '/' https://github.com/elastic/elasticsearch/issues/14594
=> fix issue with ElasticSearch not supporting '.' in fieldnames

src/Serilog.Sinks.Elasticsearch/Serilog.Sinks.Elasticsearch.csproj
Without this change this sink does not work for serilog 1.5.* w/o a redirect
=> Do not depend on specific version of serilog

CHANGES.md, README.md, appveyor.yml, src/Serilog.Sinks.Elasticsearch/Serilog.Sinks.ElasticSearch.Symbols.nuspec, src/Serilog.Sinks.Elasticsearch/Serilog.Sinks.ElasticSearch.nuspec, src/Serilog.Sinks.Elasticsearch/Serilog.Sinks.Elasticsearch.csproj, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticSearchLogShipper.cs, src/Serilog.Sinks.Elasticsearch/packages.config, test/Serilog.Sinks.Elasticsearch.Tests/ElasticsearchSinkTestsBase.cs, test/Serilog.Sinks.Elasticsearch.Tests/Serilog.Sinks.Elasticsearch.Tests.csproj, test/Serilog.Sinks.Elasticsearch.Tests/Templating/SendsTemplateHandlesUnavailableServerTests.cs, test/Serilog.Sinks.Elasticsearch.Tests/app.config, test/Serilog.Sinks.Elasticsearch.Tests/packages.config
Trying to address #45.
Updated Serilog.Sinks.Elasticsearch and Serilog.Sinks.Elasticsearch.Tests to use Serilog 2.0 (including adding references to the newer nuget packages for PeriodicBatching, RollingFile, etc.).
Also updated all the nuget dependencies to the latest versions:
- In main project: Elasticsearch.Net 2.3.3
- In test project: Elasticsearch.Net, NEST, FakeItEasy, FluentAssertions, NUnit.
Unit tests are passing, but haven't run integration tests with a real elasticsearch instance.
Also, I haven't touched serilog-sinks-elasticsearch-net40.sln; I believe Serilog 2.0 dropped support for .NET 4.0, so not sure what should be done with this :)
Hope this helps, please let me know if anything else would be required!
Thanks,
chuwik
=> Upgrading solution to Serilog 2.0

src/Serilog.Sinks.Elasticsearch/Serilog.Sinks.Elasticsearch-net40.csproj, src/Serilog.Sinks.Elasticsearch/Serilog.Sinks.Elasticsearch.csproj, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticSearchLogShipper.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ExponentialBackoffConnectionSchedule.cs
Unfortunately we're stuck on ES 1.5 so have to stick with the 2.x clients, however with our production workloads the exponential backoff functionality is very important for when we need to perform cluster maintenance. I've backported the code from 4.x and everything works great.
I've created a temporary package in nuget for anyone who wants this feature today:
https://www.nuget.org/packages/Serilog.Sinks.Elasticsearch.Backoff/2.2.0
Thanks,
=> Backport exponential backoff into v2

CHANGES.md, README.md
`ExceptionAsObjectJsonFormatter` was incorrectly written as `ExceptionAsJsonObjectFormatter` in the documentation.
=> Corrected spelling of ExceptionAsObjectJsonFormatter

README.md, src/Serilog.Sinks.Elasticsearch/LoggerConfigurationElasticSearchExtensions.cs
#87 developers can specify http headers in the config file like:
<add key="serilog:write-to:Elasticsearch.connectionGlobalHeaders" value="Authorization=Bearer SOME-TOKEN;OtherHeader=OTHER-HEADER-VALUE" />
for elastic servers that require Authorization header.
the parameter is not mandatory.
this solves also issue #75
=> #87 Add Support for specifying Http Headers in config

src/Serilog.Sinks.Elasticsearch/LoggerConfigurationElasticSearchExtensions.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchSinkOptions.cs
Sinks don't normally restrict the minimum log event level unless explicitly told to do so. The configuration overload accepting `ElasticsearchSinkOptions` respects this convention, but the appsettings compatible overload does not.
The change removes this default limitation. This might be surprising to some users - if we want to go so far as to consider it a major-version incrementing breaking change, we might wish to also rename the parameter `restrictedToMinimumLevel`, which is the name used by all other Serilog sinks for this (ES is alone in calling this parameter `minimumLogEventLevel`).
Thoughts?
Fixes #93.
=> Don't restrict to Information level when no mum is specified

README.md
I noticed a typo in the ReadMe file (unless you meant "nog")
no
=> correct 'nog' to 'not'

src/Serilog.Sinks.Elasticsearch/LoggerConfigurationElasticSearchExtensions.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchSinkOptions.cs
Allows the sink to be passed a `LoggingLevelSwitch` object as an alternative to a plain minimum log level. See #138.
No. The switch is the last argument in the public method in which it appears.
I don't think unit tests would be appropriate here since all the code is in Serilog itself, the PR simply passes in an extra argument. 
I've tested it manually and the switches operate correctly as expected (open two ES sinks, pass different switches, set different minimum levels, log only goes to one).
=> Added logLevelSwitch option

src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticSearchSink.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchSinkOptions.cs
[Add support for PipelineDecider](https://github.com/serilog/serilog-sinks-elasticsearch/issues/135)
No
=> Add support for dynamic Pipeline

src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticSearchTemplateProvider.cs, test/Serilog.Sinks.Elasticsearch.Tests/Templating/template_v6.json
#140 - issue in 6.1, where value for index in index template must be a boolean. 
No, not with the new template option to specify ES version. Change only impacts 6.x template.
Changed: ShouldRegisterTheCorrectTemplateOnRegistration 
=> Fix field index option for 6.1+ template to use boolean value.

sample/Serilog.Sinks.Elasticsearch.Sample/Serilog.Sinks.Elasticsearch.Sample.csproj, src/Serilog.Sinks.Elasticsearch/Properties/AssemblyInfo.cs, src/Serilog.Sinks.Elasticsearch/Serilog.Sinks.ElasticSearch.Symbols.nuspec, src/Serilog.Sinks.Elasticsearch/Serilog.Sinks.ElasticSearch.nuspec, src/Serilog.Sinks.Elasticsearch/Serilog.Sinks.Elasticsearch.csproj, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticSearchLogShipper.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticSearchSink.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchSinkState.cs, test/Serilog.Sinks.Elasticsearch.Tests/Discrepancies/ElasticsearchDefaultSerializerTests.cs, test/Serilog.Sinks.Elasticsearch.Tests/Discrepancies/JsonNetSerializerTests.cs, test/Serilog.Sinks.Elasticsearch.Tests/ElasticsearchSinkTestsBase.cs, test/Serilog.Sinks.Elasticsearch.Tests/Serilog.Sinks.Elasticsearch.Tests.csproj
#152 
Allows the use of serilog-sinks-elasticsearch in projects that use NEST 6 and elasticseatch-net 6
yes; not directly but transitively because elasticsearch-net v6 has breaking changes from v5.x
=> Updated to elasticsearch 6 libraries

src/Serilog.Sinks.Elasticsearch/LoggerConfigurationElasticSearchExtensions.cs
=> Extend LoggerConfiguration.Elasticsearch with additional attributes

README.md
It took me a while to figure out that the reason the sink failed to start with a somewhat cryptic "Failed to execute" error was that, while I had updated all libraries to ES6-compatibile versions, I had not set the  `AutoRegisterTemplateVersion` option and so the template sent was not ES6-compatible (it used "string").
This PR explains this snag in the readme.
Note: for a future PR, would it make sense to deprecate the manual option and automatically detect the ES version when attempting to register a template? It can be fetched by a GET request at the root URL, which returns:
```    {
"name" : "8hV7EYy",
"cluster_name" : "docker-cluster",
"cluster_uuid" : "bC1bTjVuTiyWoaprIIZIIw",
"version" : {
"number" : "6.2.1",
"build_hash" : "7299dc3",
"build_date" : "2018-02-07T19:34:26.990113Z", …
```
=> Explain use of `AutoRegisterTemplateVersion` in the README

src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/DefaultJsonFormatter.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchJsonFormatter.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchSinkOptions.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchSinkState.cs, test/Serilog.Sinks.Elasticsearch.Tests/ElasticsearchJsonFormatterTests.cs
#158
#159
Nop
Sorry I should have made 2 distinct PR
=> Render message by default , Could disable MessageTemplate

README.md, src/Serilog.Sinks.Elasticsearch/LoggerConfigurationElasticSearchExtensions.cs
=> Expose interface-typed options via appsettings

CHANGES.md, README.md, src/Serilog.Sinks.Elasticsearch/LoggerConfigurationElasticSearchExtensions.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/DefaultJsonFormatter.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchJsonFormatter.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchSinkOptions.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchSinkState.cs, test/Serilog.Sinks.Elasticsearch.Tests/ElasticsearchJsonFormatterTests.cs
=> Merge dev to master

appveyor.yml
Post moving to NuGet orgs (see #1159) a new key is needed to push packages.  Current [builds](https://ci.appveyor.com/project/serilog/serilog/build/977) are failing.
The API key has been created under the Serilog org in NuGet.
No
=> New NuGet API Key

src/Serilog.Sinks.Elasticsearch/LoggerConfigurationElasticSearchExtensions.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticSearchLogShipper.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchSinkOptions.cs, test/Serilog.Sinks.Elasticsearch.Tests/ElasticSearchLogShipperTests.cs
- For enhancement request #166
- No
- New option : SingleEventSizePostingLimit (default to 0: no limit)
- Remove redundant overload method in LoggerConfigurationElasticSearchExtensions.cs
=> feature: add option to skip sending oversized data to Elasticsearch

sample/Serilog.Sinks.Elasticsearch.Sample/Program.cs
FileSink() is deprecated and the example text generates a warning message.
No
=> Changed FailureSink from FileSink(deprecated) to RollingFileSink

src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticSearchTemplateProvider.cs, test/Serilog.Sinks.Elasticsearch.Tests/Templating/template_v6.json
fixes #206 
afaict NO
This only fixes the error, a follow-up deprecation warning `#! Deprecation: [_default_] mapping is deprecated since it is not useful anymore now that indexes cannot have more than one type` is not addressed.
=> for ES v6 use "index_patterns" instead of "template" field

README.md, sample/Serilog.Sinks.Elasticsearch.Sample/Serilog.Sinks.Elasticsearch.Sample.csproj
Target of Sample project was downgraded from `netcoreapp2.1` to `netcoreapp2.0` due to `2.1.4` sdk version in `global.json`. With higher version of sdk, `build.ps1` doesn't work correctly.
=> Notes about formatters in readme

src/Serilog.Formatting.Elasticsearch/Serilog.Formatting.Elasticsearch.csproj, src/Serilog.Sinks.Elasticsearch/Serilog.Sinks.Elasticsearch.csproj, test/Serilog.Sinks.Elasticsearch.Tests/Discrepancies/ElasticsearchSinkUniformityTestsBase.cs, test/Serilog.Sinks.Elasticsearch.Tests/Serilog.Sinks.Elasticsearch.Tests.csproj
to fix #210 and fix #196  
A few comments about changes:
* `DOTNETCORE` constant is used only in tests projects. By this reason it was removed from `Serilog.Formatting.Elasticsearch` and `Serilog.Sinks.Elasticsearch` projects
* `NO_SERIALIZATION` and `NO_TIMER` constants are not used in `Serilog.Sinks.Elasticsearch` project and was removed from `netstandard1.3` target framework
* [System.Exception.GetObjectData](https://docs.microsoft.com/en-us/dotnet/api/system.exception.getobjectdata?view=netframework-4.7.2#applies-to) is accessible in netstandard2.0, however [`ExceptionMethod` is initialized with `null` value](https://github.com/dotnet/coreclr/blob/526c32c221192cd5876239b2d72c68d1ba0c40c3/src/System.Private.CoreLib/src/System/Exception.cs#L447). So, there was introduced new compilation …
=> add .netstandard2.0 target

sample/Serilog.Sinks.Elasticsearch.Sample/Serilog.Sinks.Elasticsearch.Sample.csproj, src/Serilog.Formatting.Elasticsearch/Serilog.Formatting.Elasticsearch.csproj, src/Serilog.Sinks.Elasticsearch/Serilog.Sinks.Elasticsearch.csproj
Update of Serilog package has two reasons:
1. Serilog 2.8.0 has separate target for .netstandard2.0;
2. Dependency graph was simplified
Serilog 2.6.0:
```plain
.NETStandard 1.3
Microsoft.CSharp (>= 4.0.1)
System.Collections (>= 4.0.11)
System.Collections.NonGeneric (>= 4.0.1)
System.Dynamic.Runtime (>= 4.0.11)
System.Globalization (>= 4.0.11)
System.Linq (>= 4.1.0)
System.Reflection (>= 4.1.0)
System.Reflection.Extensions (>= 4.0.1)
System.Runtime (>= 4.1.0)
System.Runtime.Extensions (>= 4.1.0)
System.Text.RegularExpressions (>= 4.1.0)
System.Threading (>= 4.0.11)
```
Serilog 2.8.0:
```plain
.NETStandard 1.3
NETStandard.Library (>= 1.6.1)
System.Collections.NonGeneric (>= 4.3.0)
.NETStandard 2.0
System.Collections.NonGeneric (>= 4.3.0)
```
=> Update serilog nuget package to 2.8.0 version

CHANGES.md, GitVersion.yaml, GitVersion.yml, appveyor.yml, src/Serilog.Formatting.Elasticsearch/DefaultJsonFormatter.cs, src/Serilog.Formatting.Elasticsearch/ElasticsearchJsonFormatter.cs, src/Serilog.Formatting.Elasticsearch/ExceptionAsObjectJsonFormatter.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchSinkOptions.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchSinkState.cs, test/Serilog.Sinks.Elasticsearch.Tests/ElasticsearchJsonFormatterTests.cs
This PR fixes #229
No. The new flag is false by default, which keeps the current behavior. If the flag is set to true the new behavior takes place.
=> Added FormatStackTraceAsArray option to write StackTrace as an array

src/Serilog.Formatting.Elasticsearch/ElasticsearchJsonFormatter.cs, test/Serilog.Sinks.Elasticsearch.Tests/ElasticsearchJsonFormatterTests.cs
#281 - Log Events not Written to Sink with Inner Exceptions.
No
A null reference exception was thrown when trying to format Exception with no stacktrace (either root or inner one). This caused log events not to be written to the Sink.
This only happens, when someone tries to log an exception that wasn't thrown, but created via the `new` keyword. The latter one has most properties set to `null` because it was not thrown. While it's rare that such instance of the Exception class is used, the formatter should still be able to handle it gently.
I think that when `formatStackTraceAsArray` is enabled, the `StackTrace` and …
=> Fix log events not being written to Sink when exception has no stacktrace

src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/Durable/Elasticsearch/ElasticsearchLogClient.cs
I fixed a logical test issue that made the code to not go through the
cleanup path when errors happened and a issue with the error message
where a ToString was called on a dictionary resulting in the type name
instead of the actual error message. I refrained from adding the
detailed errors provided by elastic, because they can be many and
ridiculously detailed
An issue with BufferCleanPayload #294
Not really, but since it may start to execute code paths not previously executed it could cause peoples bugs to surface 
- [ X] The commit follows our [guidelines](https://github.com/serilog/serilog/blob/dev/CONTRIBUTING.md)
=> Fixed two issues regarding BufferCleanPayload

src/Serilog.Formatting.Elasticsearch/ExceptionAsObjectJsonFormatter.cs
Missing parameter for the ExceptionAsObjectJsonFormatter.
Don't want to render MessageTemplate.
=> ExceptionAsObjectJsonFormatter add renderMessageTemplate param

src/Serilog.Sinks.Elasticsearch/LoggerConfigurationElasticSearchExtensions.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchSinkOptions.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchSinkState.cs
NO
added templateCustomSettings to sink constructor for configurations loaded from settings.json file
=> templateCustomSettings loaded from settings.json file

src/Serilog.Sinks.Elasticsearch/Serilog.Sinks.Elasticsearch.csproj, test/Serilog.Sinks.Elasticsearch.IntegrationTests/Bootstrap/ClientTestClusterBase.cs, test/Serilog.Sinks.Elasticsearch.IntegrationTests/Bootstrap/SerilogSinkElasticsearchXunitRunOptions.cs, test/Serilog.Sinks.Elasticsearch.IntegrationTests/Bootstrap/XunitBootstrap.cs, test/Serilog.Sinks.Elasticsearch.IntegrationTests/Elasticsearch6/Bootstrap/Elasticsearch6XTestBase.cs, test/Serilog.Sinks.Elasticsearch.IntegrationTests/Elasticsearch6/Elasticsearch6X.cs, test/Serilog.Sinks.Elasticsearch.IntegrationTests/Elasticsearch6/Elasticsearch6XUsing7X.cs, test/Serilog.Sinks.Elasticsearch.IntegrationTests/Elasticsearch7/Bootstrap/Elasticsearch7XCluster.cs, test/Serilog.Sinks.Elasticsearch.IntegrationTests/Elasticsearch7/Bootstrap/Elasticsearch7XTestBase.cs, test/Serilog.Sinks.Elasticsearch.IntegrationTests/Elasticsearch7/Elasticsearch7X.cs, test/Serilog.Sinks.Elasticsearch.IntegrationTests/Elasticsearch7/Elasticsearch7XUsing6X.cs, test/Serilog.Sinks.Elasticsearch.IntegrationTests/Serilog.Sinks.Elasticsearch.IntegrationTests.csproj, test/Serilog.Sinks.Elasticsearch.Tests/Serilog.Sinks.Elasticsearch.Tests.csproj
Issue #340.
None in Serilog.Sinks.Elasticsearch.
There were a few breaking changes in Elasticsearch.Net between v7.0.0–v7.8.1 but the sink is not affected by them as far as I could tell and test.
I had to introduce two extra changes for the upgrade:
1. Upgrade `Microsoft.CSharp` v4.5.0 → v4.6.0 because it was upgraded in Elasticsearch.Net as well.
1. Replace `Elastic.Managed` and `Elastic.Xunit` packages in the integration tests with the newer `Elastic.Elasticsearch.Managed` and `Elastic.Elasticsearch.Xunit`. The old packages were deleted from the Elastic Abstractions CI feed and not available anymore.
I ran the existing unit and …
=> Upgrade Elasticsearch.Net to 7.8.1 

.github/ISSUE_TEMPLATE.md
Just a small spelling issue.
No.
No unit test needed I would say 😅
=> Fixed small spelling issue in issue template.

src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticSearchSink.cs
https://github.com/serilog/serilog-sinks-elasticsearch/issues/346
No
cc: @mivano
=> add async methods

src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticSearchSink.cs
#357
No, ExpandoObject is already an IDictionary<string, object>
=> Fix HasProperty when settings is a Dictionary

.vscode/settings.json, Build.ps1
=> use snupkg

CHANGES.md, README.md, src/Serilog.Sinks.Elasticsearch/LoggerConfigurationElasticSearchExtensions.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/Durable/Elasticsearch/DurableElasticsearchSink.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/Durable/Elasticsearch/ElasticsearchLogClient.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/Durable/Elasticsearch/ElasticsearchPayloadReader.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticSearchSink.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchSinkOptions.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchSinkState.cs, test/Serilog.Sinks.Elasticsearch.Tests/BulkActionTests.cs, test/Serilog.Sinks.Elasticsearch.Tests/ElasticsearchSinkTestsBase.cs
In order to write to data streams we'll need to set the
`op_type` to `create` the default is `index`
In order to don't serialize null values for the batch action and to not depend
on custom serialization setting we're using `LowLevelRequestResponseSerializer.Instance`
for serialization of the action.
We won't throw exception when setting the TypeName to null since:
- This is deprecated in v7
- Won't work in v8
- #355 It's possible to set the op_type to create by setting `BatchAction` to `ElasticOpType.Create`
- #345 It's possible to set `TypeName` to `null` to remove it from the payload being sent to Elastic.
I don't think we have introduced an breaking change but we'll need to review the following changes …
=> Added support for controlling the op_type when indexing

README.md
=> Corrected docs for batchAction config

CHANGES.md, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchSinkState.cs, test/Serilog.Sinks.Elasticsearch.Tests/BulkActionTests.cs
Fixes a regression introduced in #356
We should override the TypeName if it's specified.
Note that there are different defaults depending
on how the options are created.
- Created from configuration it defaults to `logevent`
- Created from code it defaults to `_doc`
#364
No
=> Override type name if specified

src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchSinkOptions.cs
The default TypeName was changed to '_doc' in #298
Correcting a documentation error.
No. It does not affect the running code.
None
=> fix: Correct comment about default TypeName

src/Serilog.Sinks.Elasticsearch/LoggerConfigurationElasticSearchExtensions.cs
Ability to set TypeName to null via appsettings.json. (Root cause of issue #375 )
No
Unable to pass most of the unit tests as they seem to need a real cluster to run towards?
TypeName was already exposed as configurable through appsettings.json but if set to null it is (by Microsofts configuration reader I belive) set to an empty string. This in turns make the already exisiting handling of TypeName in the sink (TypeName is deprecated in Elastic 7.x and unsopported (posts get 400 reply) in Elastic 8.x) not work as intentended.
=> Proper handling of TypeName = null from appsettings.json

src/Serilog.Sinks.Elasticsearch/LoggerConfigurationElasticSearchExtensions.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticSearchSink.cs
Cleaning up a few very minor typos in internal methods or exposed via
IntelliSense:
* "semi column" -> "semi-colon"
* "preforming" -> "performing"
* "CreatePlayLoad" -> "CreatePayload"
No.
=> Fix internal or IntelliSense typos

serilog-sinks-elasticsearch.sln
Fixing the error when opening `serilog-sinks-elasticsearch.sln` in Visual Studio
No.
=> fix file references in the Visual Studio Solution file.

src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchVersionManager.cs, test/Serilog.Sinks.Elasticsearch.Tests/ElasticsearchSinkTests.cs, test/Serilog.Sinks.Elasticsearch.Tests/Stubs/ConnectionStub.cs, test/Serilog.Sinks.Elasticsearch.Tests/Templating/DiscoverVersionTests.cs
This PR addresses issue #270, Elasticsearch version is now read from the root product page response, which does not require additional privileges.
Unit-test stubs have been adapted to this change as well.
No.
=> Read Elasticsearch server version from a root page response

src/Serilog.Formatting.Elasticsearch/Serilog.Formatting.Elasticsearch.csproj, src/Serilog.Sinks.Elasticsearch/Serilog.Sinks.Elasticsearch.csproj
Disable `PublicSign` to fix strong-name signature verification issue of assemblies from public NuGet package:
Issue with signing of assemblies published in NuGet package.
> Could not load file or assembly 'Serilog.Formatting.Elasticsearch' or one of its dependencies. Strong name signature could not be verified. The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)"
No.
**Notes**
Fix is based on similar issue fixed in another Serilog Sink [here](https://github.com/whir1/serilog-sinks-graylog/issues/5) and on further details about "Public Sign" from …
=> #498 Disable `PublicSign` to fix strong-name signature verification issue

README.md
This sink supported (even if unintentionally) Opensearch and was a go-to solution for people using it up until the last version - 
Updated Elasticsearch packages no longer support writing to Opensearch.
No
Issue #508
=> updated readme about opensearch support

sample/Serilog.Sinks.Elasticsearch.Sample/Program.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticSearchSink.cs, src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchSinkOptions.cs
#381 
Yes
At first I thought it would be nice to populate the Exception in the Logevent but unfortunately it had no setter. So had to be a breaking change instead
=> Added original exception to FailureCallback action
